version: '3.8'

services:

  nginx:
    image: library/nginx:stable-alpine
    restart: unless-stopped
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    volumes:
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - public:/var/www/html/public
    ports:
      - 80:80

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: production
    env_file:
      - .env
    volumes:
    - public:/mnt/public
    command: >
      sh -c "
        rm -rf /mnt/public/* &&
        cp -r ./public /mnt/ &&
        php artisan config:cache &&
        php artisan migrate --force &&
        php-fpm -F
      "
    depends_on:
      - database

  database:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 5
      timeout: 5s
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  db_data:
  public: # used to transfer public directory files between php and nginx containers
