apiVersion: apps/v1
kind: Deployment
metadata:
  name: un-acoperis-deploy
  labels:
    app: un-acoperis
spec:
  replicas: 1
  template:
    metadata:
      name: un-acoperis-deploy
      labels:
        app: un-acoperis
    spec:
      volumes:
        - name: public-dir
          emptyDir: {}
      initContainers:
        ## copy public directory to a separate volume which will be mounted to nginx root.
        - name: copy-public
          image: code4romania/un-acoperis
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt/public
              name: public-dir
      containers:
        - name: php
          image: code4romania/un-acoperis
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["php", "artisan", "config:cache"]
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          envFrom:
            - secretRef:
                name: un-acoperis-secret
                optional: true
        - name: nginx
          image: library/nginx:stable
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/public
              name: public
      restartPolicy: Always
  selector:
    matchLabels:
      app: un-acoperis-deploy
